import type { GeneratedFile } from '../index'

/**
 * Files the lobby template references that the game does not already ship.
 *
 * GENERATED by scripts/import-lobby-assets.mjs — do not edit by hand.
 *
 * Empty for the built-in fallback lobby, which deliberately references stock
 * assets only. Importing a hand-authored lobby fills this in; binary files are
 * carried as base64 and written back out by src/main/packer.ts.
 */
export const LOBBY_ASSETS: readonly GeneratedFile[] = []
