/**
 * The lobby level, verbatim.
 *
 * GENERATED by scripts/import-lobby-assets.mjs — do not edit by hand.
 * Source: D:/Program Files (x86)/Steam/steamapps/common/Hammerwatch/editor/pht6_quiky_dreadmann_mansion/levels/test_lobby.xml
 *
 * Treated as an opaque swappable template: buildLobby() rewrites four things
 * in it by id (vendor `cats`, badge doodad paths, the items list — diamonds and
 * free upgrades both — and the exit's target level) and touches nothing else.
 * Nothing here is re-serialized through src/generator/xml/, and no value is
 * drawn from either RNG stream.
 *
 * The two warm lights at the shop end (ids 3400/3401) come from the source
 * level and are unconditional — there is no parameter for them. Lights are
 * never renumbered at build time, so they had to be given authored-range ids up
 * front: the ids they carry in the source level sit inside the span the diamond
 * payout walks, and a deep enough pile would have landed on top of them.
 */
import { MAX_DIAMOND_COUNT } from '../levelTemplate/surgery'
import type { UpgradeSlots } from '../levelTemplate/surgery'

export const LOBBY_TEMPLATE = `<dictionary>
	<dictionary name="tilemap">
		<array name="tiledata">
			<dictionary>
				<int name="x">0</int>
				<int name="y">-20</int>
				<array name="datasets">
					<dictionary>
						<string name="tileset">tilemaps/c_tiles.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 1 4 4 3 3 2 3 2 2 1 4 3 3 1 0 0 0 0 4 4 4 3 3 4 2 3 2 1 4 1 3 4 1 1 0 0 1 3 2 1 2 3 3 2 1 2 1 3 4 4 2 1 3 3 2 2</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255</int-arr>
					</dictionary>
				</array>
			</dictionary>
			<dictionary>
				<int name="x">-20</int>
				<int name="y">0</int>
				<array name="datasets">
					<dictionary>
						<string name="tileset">tilemaps/c_tiles.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 4 4 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 4 1 1 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 2 3 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 1 3 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
				</array>
			</dictionary>
			<dictionary>
				<int name="x">0</int>
				<int name="y">0</int>
				<array name="datasets">
					<dictionary>
						<string name="tileset">tilemaps/b_tiles_red.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_tiles.xml</string>
						<int-arr name="data-t">3 3 3 2 1 3 4 4 2 1 4 2 3 1 4 2 3 1 3 4 3 2 3 4 2 3 4 4 2 3 3 1 4 3 4 2 1 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 4 1 3 1 2 1 4 0 0 0 0 4 1 1 1 2 4 2 3 2 2 1 3 2 2 3 1 0 0 0 0 3 1 3 1 3 2 1 3 1 4 2 2 4 1 1 2 0 0 0 0 2 3 2 3 2 2 2 2 4 2 2 2 2 1 4 4 0 0 0 0 4 2 2 3 3 2 1 2 3 4 4 1 1 4 2 1 0 0 0 0 1 3 2 2 4 1 3 3 4 1 2 2 4 2 1 3 0 0 0 0 4 1 4 1 2 1 4 3 1 3 3 4 2 3 4 3 0 0 0 0 2 4 3 2 4 1 4 2 2 4 4 2 3 2 2 4 0 0 0 0 2 3 1 3 4 1 4 2 2 2 1 2 3 3 3 4 0 0 0 0 1 4 1 2 2 2 2 3 1 1 3 3 3 2 1 2 0 0 0 0 3 3 1 2 1 1 1 2 2 2 1 1 1 3 2 3 0 0 0 0 3 1 4 2 2 4 4 2 4 2 2 1 2 2 3 2 0 0 0 0 3 1 4 4 1 4 4 2 4 2 2 4 4 1 4 3 0 0 0 0 2 4 4 2 4 1 4 4 1 3 1 1 3 4 4 3 0 0 0 0 2 4 1 3 4 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 4 4 3 1 3 2 3 1 4 2 3 2 4 4 1 4 1 2 1 4 3 1 3 2 1 4 2 2 1 4 1 1 1 2 1 3 3 4</int-arr>
						<int-arr name="data-a">255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 255 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_default_border_dn.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_default_border_l.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_default_border_r.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_default_border_up.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
				</array>
			</dictionary>
			<dictionary>
				<int name="x">20</int>
				<int name="y">0</int>
				<array name="datasets">
					<dictionary>
						<string name="tileset">tilemaps/b_tiles_red.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
					<dictionary>
						<string name="tileset">tilemaps/c_tiles.xml</string>
						<int-arr name="data-t">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
				</array>
			</dictionary>
			<dictionary>
				<int name="x">0</int>
				<int name="y">20</int>
				<array name="datasets">
					<dictionary>
						<string name="tileset">tilemaps/c_tiles.xml</string>
						<int-arr name="data-t">4 1 1 4 3 1 1 1 3 3 3 3 3 2 3 1 3 4 3 3 2 1 4 3 2 3 4 2 4 1 4 3 1 4 2 3 4 1 3 4 4 2 1 3 4 1 2 1 3 3 3 3 4 4 1 3 3 3 1 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
						<int-arr name="data-a">255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</int-arr>
					</dictionary>
				</array>
			</dictionary>
		</array>
	</dictionary>
	<dictionary name="doodads">
		<array name="doodads">
			<dictionary>
				<int name="id">42</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">47</int>
				<string name="type">doodads/level1/c_crn_l_up.xml</string>
				<vec2 name="pos">-11 -13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">48</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">6 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">49</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">4 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">50</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">2 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">51</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">0 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">52</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-2 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">53</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-4 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">54</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-6 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">55</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-8 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">60</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-10 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">61</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">8 -12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">73</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">-7.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">74</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">-4.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">75</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">-1.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">76</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">1.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">77</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">4.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">78</int>
				<string name="type">doodads/generic/lamp_torch.xml</string>
				<vec2 name="pos">7.5 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">39</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">158</int>
				<string name="type">doodads/level1/c_crn_r_up.xml</string>
				<vec2 name="pos">10 -13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">1</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-16 0</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">2</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-16 -2</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">4</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 -5</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">5</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 5</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">6</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">19</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 9</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">40</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 -7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">41</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 -9</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3336</int>
				<string name="type">doodads/level1/c_crn_l_up.xml</string>
				<vec2 name="pos">-16 -4</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3337</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-15 -3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3338</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-13 -3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3339</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-15 4</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3340</int>
				<string name="type">doodads/level1/c_h_16.xml</string>
				<vec2 name="pos">-13 4</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3341</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-16 2</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3342</int>
				<string name="type">doodads/level1/c_crn_r_up.xml</string>
				<vec2 name="pos">-11 3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3343</int>
				<string name="type">doodads/level1/c_crn_l_dn.xml</string>
				<vec2 name="pos">-16 4</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3345</int>
				<string name="type">doodads/level1/c_crn_r_dn.xml</string>
				<vec2 name="pos">-11 -3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">180</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">-1 6</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">183</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">3 6</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">184</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">-1 -8</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">185</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">3 -8</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">186</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">-8 7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">187</int>
				<string name="type">doodads/lamp_torch_post_spor.xml</string>
				<vec2 name="pos">8 7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3314</int>
				<string name="type">doodads/generic/exit_teleport_stand.xml</string>
				<vec2 name="pos">7 0</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3315</int>
				<string name="type">doodads/generic/exit_teleport.xml</string>
				<vec2 name="pos">7 0</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">10</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">11</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -5</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">37</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">144</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 3</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">145</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 1</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">146</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -1</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">148</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 5</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">171</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 -9</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">16</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 9</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">13</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 7</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">21</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">20</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">-11 11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">23</int>
				<string name="type">doodads/level1/c_v_cap_dn.xml</string>
				<vec2 name="pos">-11 15</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">27</int>
				<string name="type">doodads/theme_c/c_ledge_up.xml</string>
				<vec2 name="pos">4 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">28</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">6 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">31</int>
				<string name="type">doodads/theme_c/c_ledge_up.xml</string>
				<vec2 name="pos">0 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">32</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">2 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">33</int>
				<string name="type">doodads/theme_c/c_ledge_up.xml</string>
				<vec2 name="pos">-4 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">34</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">-2 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">35</int>
				<string name="type">doodads/theme_c/c_ledge_up.xml</string>
				<vec2 name="pos">-8 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">36</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">-6 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">56</int>
				<string name="type">doodads/special/vendor_combo.xml</string>
				<vec2 name="pos">-8 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">57</int>
				<string name="type">doodads/special/vendor_defense.xml</string>
				<vec2 name="pos">-4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">58</int>
				<string name="type">doodads/special/vendor_misc.xml</string>
				<vec2 name="pos">0 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">59</int>
				<string name="type">doodads/special/vendor_offense.xml</string>
				<vec2 name="pos">4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">62</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">8 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">63</int>
				<string name="type">doodads/theme_c/c_ledge_up_v2.xml</string>
				<vec2 name="pos">-10 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">64</int>
				<string name="type">doodads/special/vendor_power.xml</string>
				<vec2 name="pos">8 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">65</int>
				<string name="type">doodads/special/vendor_speech_combo.xml</string>
				<vec2 name="pos">-8 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">66</int>
				<string name="type">doodads/special/vendor_speech_defense.xml</string>
				<vec2 name="pos">-4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">67</int>
				<string name="type">doodads/special/vendor_speech_misc.xml</string>
				<vec2 name="pos">0 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">68</int>
				<string name="type">doodads/special/vendor_speech_offense.xml</string>
				<vec2 name="pos">4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">69</int>
				<string name="type">doodads/special/vendor_speech_power.xml</string>
				<vec2 name="pos">8 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3346</int>
				<string name="type">doodads/special/vendor_speech_level5.xml</string>
				<vec2 name="pos">0 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3347</int>
				<string name="type">doodads/special/vendor_speech_level5.xml</string>
				<vec2 name="pos">4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3348</int>
				<string name="type">doodads/special/vendor_speech_level5.xml</string>
				<vec2 name="pos">-4 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">3349</int>
				<string name="type">doodads/special/vendor_speech_level5.xml</string>
				<vec2 name="pos">-8 12</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">17</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 11</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">18</int>
				<string name="type">doodads/level1/c_v_16.xml</string>
				<vec2 name="pos">10 13</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
			<dictionary>
				<int name="id">22</int>
				<string name="type">doodads/level1/c_v_cap_dn.xml</string>
				<vec2 name="pos">10 15</vec2>
				<bool name="need-sync">False</bool>
			</dictionary>
		</array>
	</dictionary>
	<dictionary name="actors">
	</dictionary>
	<dictionary name="items">
		<array name="items/valuable_diamond_red.xml">
			<array><int>94</int><vec2>-4.5 -10</vec2></array>
			<array><int>95</int><vec2>-1.5 -10</vec2></array>
			<array><int>96</int><vec2>1.5 -10</vec2></array>
			<array><int>97</int><vec2>4.5 -8</vec2></array>
			<array><int>3331</int><vec2>-4.5 -8</vec2></array>
			<array><int>3332</int><vec2>-1.5 -8</vec2></array>
			<array><int>3333</int><vec2>1.5 -8</vec2></array>
			<array><int>3334</int><vec2>4.5 -10</vec2></array>
			<array><int>3350</int><vec2>7.5 -8</vec2></array>
			<array><int>3351</int><vec2>7.5 -10</vec2></array>
			<array><int>3352</int><vec2>-7.5 -10</vec2></array>
			<array><int>3353</int><vec2>-7.5 -8</vec2></array>
			<array><int>3354</int><vec2>-7.5 -10</vec2></array>
			<array><int>3356</int><vec2>-4.5 -8</vec2></array>
			<array><int>3355</int><vec2>-4.5 -10</vec2></array>
			<array><int>3357</int><vec2>-7.5 -8</vec2></array>
			<array><int>3358</int><vec2>-1.5 -10</vec2></array>
			<array><int>3359</int><vec2>-1.5 -8</vec2></array>
			<array><int>3360</int><vec2>1.5 -10</vec2></array>
			<array><int>3361</int><vec2>1.5 -8</vec2></array>
			<array><int>3362</int><vec2>4.5 -10</vec2></array>
			<array><int>3363</int><vec2>4.5 -8</vec2></array>
			<array><int>3364</int><vec2>7.5 -10</vec2></array>
			<array><int>3365</int><vec2>7.5 -8</vec2></array>
		</array>
	</dictionary>
	<dictionary name="scripting">
		<array name="nodes">
			<dictionary>
				<int name="id">15</int>
				<string name="type">LevelStart</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">-13 0</vec2>
				<dictionary name="parameters">
					<int name="id">0</int>
					<int name="dir">2</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">228</int>
				<string name="type">RectangleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">7 0</vec2>
				<dictionary name="parameters">
					<float name="w">3</float>
					<float name="h">3</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3295</int>
				<string name="type">ShopArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">8 8.5</vec2>
				<dictionary name="parameters">
					<string name="cats">power</string>
					<dictionary name="shape">
						<int-arr name="static">3294</int-arr>
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3297</int>
				<string name="type">ShopArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">4 8.5</vec2>
				<dictionary name="parameters">
					<string name="cats">off1 off2 off3 off4 off5</string>
					<dictionary name="shape">
						<int-arr name="static">3296</int-arr>
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3305</int>
				<string name="type">ShopArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">0 8.5</vec2>
				<dictionary name="parameters">
					<string name="cats">misc1 misc2 misc3 misc4 misc5</string>
					<dictionary name="shape">
						<int-arr name="static">3304</int-arr>
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3307</int>
				<string name="type">ShopArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">-4 8.5</vec2>
				<dictionary name="parameters">
					<string name="cats">def1 def2 def3 def4 def5</string>
					<dictionary name="shape">
						<int-arr name="static">3306</int-arr>
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3310</int>
				<string name="type">ShopArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">-8 8.5</vec2>
				<dictionary name="parameters">
					<string name="cats">combo1 combo2 combo3 combo4 combo5</string>
					<dictionary name="shape">
						<int-arr name="static">3309</int-arr>
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">231</int>
				<string name="type">AllPlayersAreaTrigger</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">14.5 1.25</vec2>
				<dictionary name="parameters">
					<dictionary name="shape">
						<int-arr name="static">228</int-arr>
					</dictionary>
					<string name="msg">Waiting all players...</string>
				</dictionary>
				<int-arr name="connections">229 232</int-arr>
				<int-arr name="connection-delays">0 0</int-arr>
			</dictionary>
			<dictionary>
				<int name="id">232</int>
				<string name="type">LevelExitArea</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">14 -2</vec2>
				<dictionary name="parameters">
					<string name="level">1</string>
					<int name="start id">0</int>
					<dictionary name="shape">
					</dictionary>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">229</int>
				<string name="type">PlaySound</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">16.75 1.25</vec2>
				<dictionary name="parameters">
					<string name="sound">sound/misc.xml:info_teleport_activate</string>
					<bool name="loop">False</bool>
					<bool name="play3d">True</bool>
					<float name="range3d">5</float>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3294</int>
				<string name="type">CircleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">8 11.75</vec2>
				<dictionary name="parameters">
					<float name="diameter">2</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3296</int>
				<string name="type">CircleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">4 11.75</vec2>
				<dictionary name="parameters">
					<float name="diameter">2</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3304</int>
				<string name="type">CircleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">0 11.75</vec2>
				<dictionary name="parameters">
					<float name="diameter">2</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3306</int>
				<string name="type">CircleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">-4 11.75</vec2>
				<dictionary name="parameters">
					<float name="diameter">2</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
			<dictionary>
				<int name="id">3309</int>
				<string name="type">CircleShape</string>
				<bool name="enabled">True</bool>
				<int name="trigger-times">-1</int>
				<vec2 name="pos">-8 11.75</vec2>
				<dictionary name="parameters">
					<float name="diameter">2</float>
					<int name="types">15</int>
				</dictionary>
			</dictionary>
		</array>
	</dictionary>
	<dictionary name="lighting">
		<array name="lights">
			<dictionary>
				<int name="id">191</int>
				<vec2 name="pos">-4.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">192</int>
				<vec2 name="pos">-1.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">193</int>
				<vec2 name="pos">1.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">194</int>
				<vec2 name="pos">4.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">195</int>
				<vec2 name="pos">7.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">196</int>
				<vec2 name="pos">-7.5 -12.5</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">202</int>
				<vec2 name="pos">-1 6</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">203</int>
				<vec2 name="pos">3 6</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">204</int>
				<vec2 name="pos">8 7</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">205</int>
				<vec2 name="pos">-8 7</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">4.9</float>
			</dictionary>
			<dictionary>
				<int name="id">206</int>
				<vec2 name="pos">-1 -8</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">3.3</float>
			</dictionary>
			<dictionary>
				<int name="id">207</int>
				<vec2 name="pos">3 -8</vec2>
				<int-arr name="mulColor1">5 153 225 255</int-arr>
				<int-arr name="mulColor2">8 88 172 255</int-arr>
				<int-arr name="mulColor3">3 119 169 255</int-arr>
				<float name="mulRange">13.8</float>
				<int-arr name="addColor1">6 163 184 255</int-arr>
				<int-arr name="addColor2">0 109 109 255</int-arr>
				<int-arr name="addColor3">1 57 66 255</int-arr>
				<float name="addRange">2.6</float>
			</dictionary>
			<dictionary>
				<int name="id">3321</int>
				<vec2 name="pos">7 1</vec2>
				<int-arr name="mulColor1">134 1 202 255</int-arr>
				<int-arr name="mulColor2">15 1 247 255</int-arr>
				<int-arr name="mulColor3">81 1 222 255</int-arr>
				<float name="mulRange">8.3</float>
				<int-arr name="addColor1">140 55 199 255</int-arr>
				<int-arr name="addColor2">2 43 205 255</int-arr>
				<int-arr name="addColor3">48 32 0 255</int-arr>
				<float name="addRange">1.6</float>
			</dictionary>
			<dictionary>
				<int name="id">3400</int>
				<vec2 name="pos">-7.75 -4</vec2>
				<int-arr name="mulColor1">255 255 255 255</int-arr>
				<int-arr name="mulColor2">255 255 224 255</int-arr>
				<int-arr name="mulColor3">255 165 0 255</int-arr>
				<float name="mulRange">15</float>
				<int-arr name="addColor1">96 64 0 255</int-arr>
				<int-arr name="addColor2">64 48 0 255</int-arr>
				<int-arr name="addColor3">48 32 0 255</int-arr>
				<float name="addRange">4</float>
			</dictionary>
			<dictionary>
				<int name="id">3401</int>
				<vec2 name="pos">8 -3.75</vec2>
				<int-arr name="mulColor1">255 255 255 255</int-arr>
				<int-arr name="mulColor2">255 255 224 255</int-arr>
				<int-arr name="mulColor3">255 165 0 255</int-arr>
				<float name="mulRange">15</float>
				<int-arr name="addColor1">96 64 0 255</int-arr>
				<int-arr name="addColor2">64 48 0 255</int-arr>
				<int-arr name="addColor3">48 32 0 255</int-arr>
				<float name="addRange">4</float>
			</dictionary>
		</array>
		<int-arr name="shadow-color">135 128 128 255</int-arr>
		<int-arr name="ambient-color">125 125 125 255</int-arr>
		<int-arr name="add-color">0 0 0 255</int-arr>
		<float name="shadow-length">1</float>
	</dictionary>
	<dictionary name="prefabs">
	</dictionary>
</dictionary>
`

/** Element ids buildLobby edits, one group per vendor stall. */
export interface LobbyVendorIds {
  /** the shape the ShopArea covers */
  shape: number
  /** the ShopArea node carrying `cats` */
  shop: number
  /** the vendor doodad */
  vendor: number
  /** the speech-bubble doodad */
  speech: number
  /** the little tier number over the vendor, or null for a single-column stall */
  badge: number | null
}

export const LOBBY_TEMPLATE_IDS: Readonly<Record<string, LobbyVendorIds>> = {
  combo: { shape: 3309, shop: 3310, vendor: 56, speech: 65, badge: 3349 },
  defense: { shape: 3306, shop: 3307, vendor: 57, speech: 66, badge: 3348 },
  misc: { shape: 3304, shop: 3305, vendor: 58, speech: 67, badge: 3346 },
  offense: { shape: 3296, shop: 3297, vendor: 59, speech: 68, badge: 3347 },
  power: { shape: 3294, shop: 3295, vendor: 64, speech: 69, badge: null }
}

/** The LevelExitArea whose target level buildLobby rewrites. */
export const LOBBY_EXIT_NODE_ID = 232

/**
 * Where the red diamonds go, in template order.
 *
 * Starting gold past one diamond per slot walks this list again rather than
 * spilling outside the room — stacking pays out in full ([VERIFIED] 2026-07-30).
 */
export const LOBBY_DIAMOND_SLOTS: ReadonlyArray<readonly [number, number]> = [
  [-7.5, -10],
  [-4.5, -10],
  [-1.5, -10],
  [1.5, -10],
  [4.5, -10],
  [7.5, -10],
  [-7.5, -8],
  [-4.5, -8],
  [-1.5, -8],
  [1.5, -8],
  [4.5, -8],
  [7.5, -8]
]

/** First id buildLobby hands to a diamond; above anything the template uses. */
export const LOBBY_ITEM_ID_BASE = 10000

/**
 * Where each free upgrade pickup goes — one slot per kind:
 * tier 1 on the back row and tier 2 in front of it.
 *
 * Read off the hand-authored level, same as the diamond slots above. A count
 * above one stacks on the kind's single slot rather than spreading, so this map
 * never has to grow with the count.
 */
export const LOBBY_UPGRADE_SLOTS: UpgradeSlots = {
  damage: [-9, -4.5],
  defense: [-8, -4.5],
  health: [-7, -4.5],
  mana: [-6, -4.5],
  damage2: [-9, -3.5],
  defense2: [-8, -3.5],
  health2: [-7, -3.5],
  mana2: [-6, -3.5]
}

/**
 * First id buildLobby hands to a free upgrade.
 *
 * Directly above the diamonds rather than a round number: the payout is capped
 * at `MAX_DIAMOND_COUNT` diamonds, so `LOBBY_ITEM_ID_BASE + MAX_DIAMOND_COUNT`
 * is the first id no diamond can reach however much gold is asked for. Derived
 * so raising that cap moves this with it instead of silently colliding.
 */
export const LOBBY_UPGRADE_ID_BASE = LOBBY_ITEM_ID_BASE + MAX_DIAMOND_COUNT
