import { XMLDictionary, XMLIntArray, XMLString } from '../xml'
import type { ThemeDef } from '../config/themes'
import type { Rand } from '../core/rand'

/**
 * The second floor tileset a paired theme stacks over its base — see the
 * `overlay` field on `ThemeDef`.
 *
 * A tile block's `datasets` is an array, and the engine happily draws several
 * tilesets into the same block; the boss arena has stacked `water` under its
 * theme since the arena shipped, and the game's own `level_bonus_1.xml` pairs
 * `bonus_1` with `bonus_shadow` the same way. This module is the one place that
 * builds the extra dataset, shared by the dungeon floors (`map/level.ts`) and
 * the arena (`boss/arena.ts`) so the two cannot drift.
 */

/** Blocks are 20x20 tiles; both callers declare them on that grid. */
const TILEMAP_CELLS = 20 * 20

function fullIntArray(name: string): XMLIntArray {
  return new XMLIntArray(name, new Array<number>(TILEMAP_CELLS).fill(255))
}

/**
 * Build the overlay dataset for one tile block, or `null` when the theme has no
 * overlay.
 *
 * Returning early — before touching `rand` — is what keeps invariant 2 intact:
 * a plain theme draws exactly the random numbers it drew before this module
 * existed, so every seed generated by an earlier build still produces
 * byte-identical output. Do not hoist the draws above the `undefined` check.
 *
 * `rand` must be the same stream the caller filled `baseDataT` from —
 * `ctx.cosmeticRand` on a dungeon floor, `ctx.bossRand` in the arena — never
 * `ctx.rand`, which carries the layout.
 *
 * @param baseDataT the block's base `data-t`, where 0 means wall/void
 */
export function overlayDataset(
  theme: ThemeDef,
  baseDataT: readonly number[],
  rand: Rand
): XMLDictionary | null {
  const overlay = theme.overlay
  if (overlay === undefined) return null

  // Full coverage: a floor cell gets a variant, a wall/void cell stays empty.
  // The two layers roll independently — sharing the base's index would tie a
  // 4-variant overlay to a 8-variant base and lose half its art.
  const dataT = baseDataT.map((t) => (t === 0 ? 0 : Math.trunc(rand.nextFloat() * overlay.tiles) + 1))

  const dict = new XMLDictionary('')
  dict.addData(new XMLString('tileset', overlay.tilemap))
  dict.addData(new XMLIntArray('data-t', dataT))
  dict.addData(fullIntArray('data-r'))
  dict.addData(fullIntArray('data-g'))
  dict.addData(fullIntArray('data-b'))
  dict.addData(dataAFromDataT(dataT))
  return dict
}

/**
 * The extra datasets a *mixed* theme stacks over its base — one per palette
 * overlay, each masked to only the cells assigned to that slot.
 *
 * Returns `[]`, having drawn nothing, when the theme has no `mixed` palette.
 * Same rule as `overlayDataset`: do not hoist a draw above that check, or every
 * seed generated by an earlier build changes.
 *
 * `cellVariant[i]` is the palette slot for cell `i`. Slot 0 is the plain base
 * and emits no dataset — those cells are simply the base layer showing through
 * uncovered. The masks are disjoint by construction, so unlike the paired-theme
 * case the relative `level` attributes of the palette's tilesets don't matter:
 * no two of them ever compete for the same cell.
 *
 * A block whose regions all landed on other slots yields no dataset for this
 * one; skipping those keeps the emitted XML near its old size instead of
 * multiplying it by the palette length. The consequence is that the number of
 * draws taken varies per block with the region layout — deterministic, since
 * the layout is, but not a fixed count.
 *
 * @param baseDataT the block's base `data-t`, where 0 means wall/void
 */
export function mixedDatasets(
  theme: ThemeDef,
  baseDataT: readonly number[],
  cellVariant: readonly number[],
  rand: Rand
): XMLDictionary[] {
  const palette = theme.mixed
  if (palette === undefined) return []

  const dicts: XMLDictionary[] = []
  for (let slot = 1; slot < palette.length; slot++) {
    const overlay = palette[slot]
    if (overlay === null) continue

    let used = false
    const dataT = baseDataT.map((t, i) => {
      if (t === 0 || cellVariant[i] !== slot) return 0
      used = true
      return Math.trunc(rand.nextFloat() * overlay.tiles) + 1
    })
    if (!used) continue

    const dict = new XMLDictionary('')
    dict.addData(new XMLString('tileset', overlay.tilemap))
    dict.addData(new XMLIntArray('data-t', dataT))
    dict.addData(fullIntArray('data-r'))
    dict.addData(fullIntArray('data-g'))
    dict.addData(fullIntArray('data-b'))
    dict.addData(dataAFromDataT(dataT))
    dicts.push(dict)
  }
  return dicts
}

/**
 * Shipped convention (Cover/wall doodads paint the rest, but the raw tile
 * layer itself should read as absent where there's no tile): `data-a` is 0
 * wherever `data-t` is the wall/void sentinel 0, 255 wherever a real floor
 * variant is drawn.
 *
 * Mandatory for an overlay specifically. The base layer sits on the void and
 * can afford a flat 255, but a layer above one must be transparent where the
 * floor stops or it paints its art out over the emptiness beyond the map.
 */
export function dataAFromDataT(dataT: readonly number[]): XMLIntArray {
  return new XMLIntArray(
    'data-a',
    dataT.map((t) => (t === 0 ? 0 : 255))
  )
}
